### PR TITLE
Ensure secure file upload for the users picture and make user profile modifiable 

### PR DESCRIPTION
**Pull request by NotTh3ta**
Updated the form in the user profile to save profile picture. Picture is saved locally in backend/media/avatar_pictures.

The profile picture filed is called "avatar" and is part of the Profile model.

The PFP upload input was part of a form to update the user profile, therefore I modified the form implementation to enable the user to modify their profile.

Response status is verified to check if profile picture was uploaded.

Resolves: #49

### CODE REVIEW

**Comment by NicholasWahome** [comment]
Looks good for me based on current changes. Changing approval of merge to Joud/Patrick as he has worked more with the UI components. To ensure it incorporates correctly with the design of the UI.

**Review by JRB958 — APPROVED** [review]
looks good! tested it out and the profile photo successfully updates. nice work!

**Comment by patrickmac3** [comment]
Tested it out manually. Successfully changed the profile photo users. looks good to me

**Comment by NicholasWahome** [comment]
@NotTh3ta You can now merge your pull request!

**Review by NicholasWahome — APPROVED** [review]

**Pull request merged**
